sudo: required

branches:
  only:
    - master

before_install: 

install: 

language: objective-c
osx_image: xcode10

script:
  - set -o pipefail && xcodebuild -project TravisTest.xcodeproj INSTALL_PATH=$HOME/bin DSTROOT=/ -configuration Release -scheme TravisTest install | xcpretty

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJBNZK5EIAHEZHTSQ
  secret_access_key: 
    secure: "bsxPFnZNHvm/AMIeP8Du+U+TTFguYsSZG9ovTMTvCt2rYtUhMs9SrMYOjovxGVlZ2FZqtbnKGL9rQCZZCV3TW0k6RaGidqGxEPRzoPs5ia299qkP8ifzHlllyrKPIN9q5p+kjk3D4e/Av4Hh0UBqgIIcDd/5vU5LrfXXu1hHpBKb2VmKzj7tW2uUeYyHJX3coLFezm4CRQxat69HqhmcLml00dXocZ1z7ExhAdGbvNWUh290CJdhpSQT6w7uGIirxyhqiVcOlS3IveLAjuscwiKa+KKLABkcKPtYgL6/8MV2h5YI14kFe6QfKon5UW+S60E/o/nl28tKi1LWXfISdyxVvqpPczhAaPkbRed33na0YhvCTSs+Ng5jtYyopb2DHL/zoSmQbTswMJfDEnTZCtnb76Uwk6ngfRU41bPpNkxfXMnwv12zZ06PPQiVL4jAcpfeh3DWcMezRPgQ9NR3MB1lyPwF97ONaNlDz8ojNuobaOYjjh2xXhfI+MhKvV6mXHt7rGJQllxrNZiCXHC6Zr1Sz2yeFF+sb9bT6XW4+wpE1TyTaQFKvg8uz5dBvud17vNrhr1SWifQLtJbQfIswJlhAJstHA05N+gzJLKZlnqyZsTAKNk5qQXL78fFEi/ClK8t8ozC7qyKhG2a/tt4mhGCfewnMDVKb4Ex2RS7ERY="
  bucket: medimach
  region: eu-west-1
  local_dir: $HOME/bin
  upload-dir: dlorenz
  acl: authenticated_read
