sudo: required

branches:
  only:
    - master

before_install: 

install: 
  - export PYTHONUSERBASE=~/.local
  - easy_install --user scan-build

language: objective-c
osx_image: xcode10

script:
  - export PATH="${HOME}/.local/bin:${PATH}" 
  - set -o pipefail && scan-build --status-bugs xcodebuild -project TravisTest.xcodeproj INSTALL_PATH=$HOME/bin DSTROOT=/ -configuration Release -scheme TravisTest install | xcpretty

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: 
  secret_access_key: 
  bucket: medimach
  region: eu-west-1
  local_dir: $HOME/bin
  upload-dir: builds/latest
  acl: authenticated_read
