sudo: required

branches:
  only:
    - master

before_install: 

install: 

language: objective-c
osx_image: xcode10

script:
  - set -o pipefail && xcodebuild -project TravisTest.xcodeproj INSTALL_PATH=$HOME/bin DSTROOT=/ -configuration Release -scheme TravisTest install | xcpretty

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id:AKIAJBNZK5EIAHEZHTSQ
  secret_access_key:
    secure:PayuzKxGOiW1OUTqwJoalbqLIraLmWVRlPWFeagbqVeR07mSBuxF0nlQSe0BwF5kx30PuQaoIZ8m+x1srix+lCfGzk26Qfe8u9TBBTKL6pj4Bw1ssjyZr6/+P/oBIttln/fvPJiYFoNAehmuQ3ZdZKYKIrH2InZGb9Oy/3BBdtt/mqeWDvBEK98z6wJBzYPkbSdlFC2AnFdPKOX9ehVbRdHeBzlOxeRpiKZPtuUx3B3W8OSCInMqa2vYcWhOANAPFySKiO2huhrYmRGp08QOO5trSDpx8VXALkLIOZW3U0zu7/7Szwnj/jWhe4ezT2+ku8jNyd08Oi08SqJztvnUzM5P29rmZT0+gnHH15JdlG74MSdUEqSHgsuVnuzGZZ/Jd+g7uM6idKdbD2uB3H6vdrRD9z4uK2x+b0y8GujMywMvK6I1IPWiI2GYBH+hisM7xnJ1GVG3lJn0XeXhAFRrl+YKXKd7Y0zPAxWzDUb3G1ffPS6U5iChfqUHGKomOQzc4JBQJnufpWMx3TCWRIg7hUHayEgTZ8KsRBuRne+J8fjxoBgEkDU/6k0/5PODAwVJ1ZC0bKx7k7Murt2KsbyxygpikBbPoR5+qTWPGezqynhPkhz/v8lyKhddtALLTo7uidlJsB7yH8lhhIeBA2i9yGhJ3gfXMfz+x/kg3Z3CIMc=
  bucket: medimach
  region: eu-west-1
  file: $HOME/bin/TravisTest
  upload-dir: dlorenz
  acl: authenticated_read
