sudo: required

branches:
  only:
    - master

before_install: 

install: 

language: objective-c
osx_image: xcode10

script:
  - set -o pipefail && xcodebuild -project TravisTest.xcodeproj INSTALL_PATH=$HOME/bin DSTROOT=/ -configuration Release -scheme TravisTest install | xcpretty

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJBNZK5EIAHEZHTSQ
  secret_access_key: 
    secure: "eIRAboh3z46Z1IFgetVEbH8aBmlrPBJdashqEMNerQkOu87FJuBJjbS7Dt1VsFlI51OKzw0Q2YOCgePSsZL/K05v1EqBvKCVEgyxNquDL2X3sTMLSTDFrT4Gy690twlBI0vXCQOgGMIaYcHeCDLROfhPyGNF1cYQhx91TFngiSACwrMQYHk5AAvuZgimDoXzb8lsc8EBThmsorLvyG4idKT7mAsmptc5zf2CaaZOysHB5t02WRglrOOQssUsjNLz70q33Rhid6iUZfg5QQn94ZpZHXwSsJ9+U+93gQCtxP7cQ/cRvpCuwHc4tvNzmGNNSURLLF9NrEPBISDJeEjVixN8Wu74QtqYmu2mJ85NY6zfNxDnOUVTV2WQnKvGgMAha6UL2noo3vOt9AqpCyxSdOG8ATIk6eePiIwYJPE/PPPgEKFpQLmMSkF4r5qxG5SpM20flUn0EGmkpPJrK1S6xk0Zx6uIzkKBWbAjTi5XaQgYPL1ZMNG3+IeOtXWyWYABOj9M94+xypCDMXj8PQvTd1gMdHaud51sj3sBHDC/DN8wWaCqiPuHZ/Pyo+z9CRQl62TbzzhCxwpldNXicx6r1pJRftxWoyUurhNGecUJv/+y8CMKpqss343Y1l8kZI1/SwJ0dBI8H7/VbRZB74orp0/kGNZkioaY+SgZE/f2leU="
  bucket: medimach
  region: eu-west-1
  local_dir: $HOME/bin
  upload-dir: dlorenz
  acl: authenticated_read
