# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzurePowerShell@4
  inputs:
    ScriptType: 'InlineScript'
    Inline: '$dateStr = (Get-Date).ToString(''yyyy-MM-dd'') 
          echo "##vso[task.setvariable variable=dateString]#$dateStr"'

- script: |
    echo my variable is $(dateString)
  displayName: 'echo var'