# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Get branch
        run: |
          echo $PATH
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: print branch
        run: |
          echo $BRANCH

      - name: install clang17
        run:   |
         sudo apt update
         sudo apt install clang-16 libc++-16-dev libc++abi-16-dev

      - name: clang version
        run: clang --version

      - name: clang-16 version
        run: clang-16 --version
        env:
          CC:   clang-16
          CXX:  clang++-16

      - name: build travis
        run: clang++-16 -std=c++20 -stdlib=libc++ main.cpp -o travis
        env:
          CC:   clang-16
          CXX:  clang++-16

      - name: run it
        run: ./travis
